src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_updated;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle(string $title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription(string $description)
    {
        $this->description = $description;

        return $this;
    }

    public function getDateUpdated()
    {
        return $this->date_updated;
    }

    public function __construct() {
        $this->date_updated = new \DateTime('now');
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId()
    {
        return $this->id;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail(string $email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername()
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles()
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword()
    {
        return (string) $this->password;
    }

    public function setPassword(string $password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/AboutController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AboutController extends AbstractController
{
    public function index()
    {
        return $this->render('about.html.twig');
    }
}

src/Controller/ContactsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ContactsController extends AbstractController
{
    public function index()
    {
        return $this->render('contacts.html.twig');
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    public function index()
    {
        return $this->render('home.html.twig');
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\News;

class NewsController extends AbstractController
{
    public function showList()
    {
        $em = $this->getDoctrine()->getManager();            
        $NewsRepo = $em->getRepository(News::class);
        
        $news_list = $NewsRepo->getNews();
        
        return $this->render('news/list.html.twig', [
            'news_list' => $news_list
        ]);
    }
    
    
    public function add(Request $req)
    {
        if($req->isMethod('POST'))
        {
            $data = $req->request->all();         
            
            $em = $this->getDoctrine()->getManager();
            
            $NewsRepo = $em->getRepository(News::class);
            
            
            if(!$NewsRepo->addNews($data)){
                return $this->render('news/exists.html.twig');
            }
                        
            return $this->render('news/success.html.twig');
        }   
        
        return $this->render('news/add.html.twig');
    }
    
    public function show($id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $News = $em->find(News::class, $id);
                
        return $this->render('news/show.html.twig', [
            'News' => $News
        ]);
    }
    
    public function delete($id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $News = $em->find(News::class, $id);
        
        $title = $News->getTitle();
        
        $em->remove($News);
        
        $em->flush();
        
        return $this->render('news/delete.html.twig', [
            'title' => $title
        ]);
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use App\Services\UserService;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
   
    public function login(AuthenticationUtils $authenticationUtils)
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }
    
    public function registration(Request $req, UserPasswordEncoderInterface $passwordEncoder)
    {
        $lastUsername = '';
        
        $isRegister = true;
        
        if($req->isMethod('POST'))
        {
            $data = $req->request->all();         
            
            $em = $this->getDoctrine()->getManager();
            
            $UserService = new UserService($passwordEncoder);
            
            $isRegister = $UserService->registr($em, $data);
            
            $lastUsername = $data['email'];
            
            if($isRegister){
                return $this->render('security/success.html.twig');
            }
        }
        
        return $this->render('security/registration.html.twig', ['last_username' => $lastUsername, 'isRegister' => $isRegister]);
    }
    
}

templates/about.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> About us </h1>
    <p>
       Building a website is, in many ways, an exercise of willpower. It’s tempting to get distracted by the bells and whistles of the design process, and forget all about creating compelling content. 
    </p>
    <p>        
        It's that compelling content that's crucial to making inbound marketing work for your business.
        So how do you balance your remarkable content creation with your web design needs? It all starts with the "About Us" page.
    </p>
    <p>
        For a remarkable about page, all you need to do is figure out your company's unique identity, and then share it with the world. Easy, right? Of course not. Your "About Us" page is one of the most important pages on your website, and it needs to be well crafted. This profile also happens to be one of the most commonly overlooked pages, which is why you should make it stand out.
    </p>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Blog news{% endblock %}</title>
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="/main.css" rel="stylesheet" />
        <script src="/jquery.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script defer src="/main.js"></script>
        {% block stylesheets %}{% endblock %}
    </head>
    <body class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand d-lg-none" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('home') }}">Home</a>
                        </li>                          
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('contacts') }}">Contacts</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('about') }}">About us</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('newsList') }}">News</a>
                        </li>                         
                    </ul>  
                    <ul class="login-form">
                        {% if app.user %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('logout') }}">Logout</a>
                        </li> 
                        <li class="nav-item">Hello: {{app.user.username}}</li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('login') }}">Login</a>
                            </li> 
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path('registration') }}">Registration</a>
                            </li>
                            <li class="nav-item">Hello: guest</li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        <div class="page">
            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/contacts.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h2 class="text-center">Contac Form</h2>
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6 pb-5">


            <!--Form with header-->

            <form action="mail.php" method="post">
                <div class="card border-primary rounded-0">
                    <div class="card-header p-0">
                        <div class="bg-info text-white text-center py-2">
                            <h3><i class="fa fa-envelope"></i> Contactanos</h3>
                            <p class="m-0">Con gusto te ayudaremos</p>
                        </div>
                    </div>
                    <div class="card-body p-3">

                        <!--Body-->
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-user text-info"></i></div>
                                </div>
                                <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre y Apellido" required>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-envelope text-info"></i></div>
                                </div>
                                <input type="email" class="form-control" id="nombre" name="email" placeholder="ejemplo@gmail.com" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text"><i class="fa fa-comment text-info"></i></div>
                                </div>
                                <textarea class="form-control" placeholder="Envianos tu Mensaje" required></textarea>
                            </div>
                        </div>

                        <div class="text-center">
                            <input type="submit" value="Enviar" class="btn btn-info btn-block rounded-0 py-2">
                        </div>
                    </div>

                </div>
            </form>
            <!--Form with header-->


        </div>
    </div>
{% endblock %}

templates/home.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> Home </h1>
{% endblock %}

templates/news/add.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> add News </h1>
    <form action="{{path('addNews')}}" method="POST">
        <div class="form-group">
            <label for="title">Title</label>
            <input name="title" type="text" class="form-control" id="title" >
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description" class="form-control" id="description" rows="3"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-primary">Add news</button>
        </div>
    </form>
{% endblock %}

templates/news/delete.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="news-date d-flex justify-content-between mb-3">
        <a href="{{ path('newsList') }}">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            News list
        </a>
    </div>
    <h1 class="removed-news"> News <span>{{title}}</span> removed success </h1>
{% endblock %}

templates/news/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> Home </h1>
{% endblock %}

templates/news/exists.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <h1> This news name alredy exists !!! </h1>
    <a class="btn btn-primary" href="{{ path('addNews') }}">Add news</a>
{% endblock %}

templates/news/list.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="d-flex align-items-center">
        <h1> List News </h1>
        {%  if is_granted('ROLE_ADMIN') %}
            <a class="btn btn-primary ml-3" href="{{path('addNews')}}" >Add news</a>
        {% endif %}
    </div>
    <div class="news-list row">        
        {% for news in news_list %}
            <div class="col-sm-12">
                <div class="row">
                    <h2 class="col-sm-8 mb-3 mt-3">{{news.title}}</h2>    
                    <div class="col-sm-4 mt-4 date-news">
                        {{news.dateUpdated|date("d m Y H:i:s")}}
                    </div>
                    <div class="col-sm-12">
                        {{news.description|slice(0,300)}} ...                        
                        <a href="{{ path('showNews', {'id': news.id}) }}" >read more</a>
                    </div>    
                </div>
            </div>
        {% endfor %}        
    </div>
{% endblock %}

templates/news/show.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="news-date d-flex justify-content-between">
        <a href="{{ path('newsList') }}">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            News list
        </a>
        <span>{{News.dateUpdated|date("d m Y H:i:s")}}</span>
    </div>
    <h1 class="news-title">{{News.title}}</h1>
    <p class="news-desc">
        {{News.description}}
    </p>    
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteNews">
        Delete news
    </button>

    <!-- Modal -->
    <div class="modal fade" id="deleteNews" tabindex="-1" role="dialog" aria-labelledby="deleteNewsLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteNewsLabel">Warning</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Do you want to delete this news ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a href="{{ path('deleteNews', {'id': News.id}) }}" class="btn btn-primary">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/news/success.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="news-date d-flex justify-content-between mb-3">
        <a href="{{ path('newsList') }}">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            News list
        </a>
    </div>
    <h1> News created success </h1>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form class="auth-form" method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form class="auth-form" method="post">
    {% if not isRegister %}
        <div class="alert alert-danger">Email already exists or password not miss match</div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Please registration</h1>
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" placeholder="Email" required autofocus>
    
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
    
    <label for="plainPassword" class="sr-only">Password</label>
    <input type="password" name="plain_password" id="plainPassword" class="form-control" placeholder="Confirm password" required>

    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    <button class="btn btn-lg btn-primary" type="submit">
        Sign in
    </button>
</form>
{% endblock %}

templates/security/success.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="news-date d-flex justify-content-between mb-3">
        <a href="{{ path('login') }}">
            <i class="fa fa-arrow-left" aria-hidden="true"></i>
            Please login page
        </a>
    </div>
    <h1> Your success registration </h1>
{% endblock %}